okxAccount01:
  name: ${env:SERVERLESS_SERVICE_NAME}-${env:AWS_STAGE}-okxAccount01
  handler: src/okxAccount01.trackBalance
  events:
    - schedule: cron(* 0/1 * * ? *)
    - httpApi:
      path: /okxAccount01
      method: post

okxAccount02:
  name: ${env:SERVERLESS_SERVICE_NAME}-${env:AWS_STAGE}-okxAccount02
  handler: src/okxAccount02.trackBalance
  events:
    - schedule: cron(* 0/1 * * ? *)
    - httpApi:
      path: /okxAccount02
      method: post

okxAccount03:
  name: ${env:SERVERLESS_SERVICE_NAME}-${env:AWS_STAGE}-okxAccount03
  handler: src/okxAccount03.trackBalance
  events:
    - schedule: cron(* 0/1 * * ? *)
    - httpApi:
      path: /okxAccount03
      method: post